/**
 * Regression Guard - Prevent Quality Regressions Across PDCA Cycles
 * @module lib/quality/regression-guard
 * @version 2.0.0
 *
 * Maintains a rule database of known issues and checks new metrics
 * against those rules to detect regressions before they ship.
 *
 * Design: docs/02-design/features/rkit-v200-enhancement.design.md Section 2.8
 * Plan: docs/01-plan/features/rkit-v200-enhancement.plan.md FR-17
 */

const path = require('path');
const stateStore = require('../core/state-store');
const { STATE_PATHS } = require('../core/paths');

// ============================================================
// Constants
// ============================================================

/** Maximum regression rules before pruning is recommended */
const MAX_REGRESSION_RULES = 200;

// ============================================================
// Storage
// ============================================================

/**
 * Get path to regression rules file.
 * @returns {string}
 */
function _rulesPath() {
  return path.join(STATE_PATHS.state(), 'regression-rules.json');
}

// ============================================================
// Rule Schema
// ============================================================

/**
 * @typedef {Object} RegressionRule
 * @property {string} id - Rule identifier (e.g., 'RR-001')
 * @property {'api'|'security'|'architecture'|'performance'|'naming'} category
 * @property {string} description - Human-readable description of the rule
 * @property {'critical'|'high'|'medium'|'low'} severity
 * @property {Object} detection - How to detect violations
 * @property {'pattern'|'metric'} detection.type - Detection method
 * @property {string} [detection.pattern] - Regex pattern string (for type=pattern)
 * @property {number} [detection.threshold] - Metric threshold (for type=metric)
 * @property {string} [detection.metricId] - Metric ID to watch (for type=metric)
 * @property {string} [detection.op] - Comparison operator (for type=metric)
 * @property {string} detectedInFeature - Feature where the issue was first found
 * @property {string} createdAt - ISO 8601 creation timestamp
 * @property {boolean} autoGenerated - Whether rule was auto-generated from iterator
 * @property {number} violations - Cumulative violation count
 */

// ============================================================
// Core Functions
// ============================================================

/**
 * Load regression rules, optionally filtered by feature and/or category.
 * @param {string} [feature] - Filter by detectedInFeature (null = all)
 * @param {string} [category] - Filter by category (null = all)
 * @returns {RegressionRule[]}
 */
function loadRules(feature, category) {
  const data = stateStore.read(_rulesPath());
  if (!data || !data.rules) return [];

  let rules = data.rules;
  if (feature) {
    rules = rules.filter(r => r.detectedInFeature === feature);
  }
  if (category) {
    rules = rules.filter(r => r.category === category);
  }
  return rules;
}

/**
 * Generate the next rule ID based on existing rules.
 * @param {RegressionRule[]} existingRules
 * @returns {string} Next ID (e.g., 'RR-042')
 * @private
 */
function _nextRuleId(existingRules) {
  let maxNum = 0;
  for (const rule of existingRules) {
    const match = rule.id && rule.id.match(/^RR-(\d+)$/);
    if (match) {
      const num = parseInt(match[1], 10);
      if (num > maxNum) maxNum = num;
    }
  }
  return `RR-${String(maxNum + 1).padStart(3, '0')}`;
}

/**
 * Add a single regression rule.
 * @param {Omit<RegressionRule, 'id'|'violations'|'createdAt'> & Partial<Pick<RegressionRule, 'id'|'violations'|'createdAt'>>} rule - Rule to add (id auto-assigned if missing)
 * @returns {string} Assigned rule ID
 */
function addRule(rule) {
  const data = stateStore.read(_rulesPath()) || { rules: [], lastUpdated: null };

  const newRule = {
    id: rule.id || _nextRuleId(data.rules),
    category: rule.category || 'architecture',
    description: rule.description || '',
    severity: rule.severity || 'medium',
    detection: rule.detection || { type: 'pattern', pattern: '' },
    detectedInFeature: rule.detectedInFeature || 'unknown',
    createdAt: rule.createdAt || new Date().toISOString(),
    autoGenerated: rule.autoGenerated != null ? rule.autoGenerated : false,
    violations: rule.violations || 0,
  };

  data.rules.push(newRule);
  data.lastUpdated = new Date().toISOString();
  stateStore.write(_rulesPath(), data);

  return newRule.id;
}

/**
 * Auto-generate regression rules from PDCA iterator results.
 * Extracts fix descriptions and creates rules to prevent recurrence.
 *
 * @param {Object} result - Iterator result object
 * @param {Array<{category?: string, description?: string, severity?: string}>} [result.fixes] - List of fixes applied
 * @param {string} feature - Feature name where fixes were applied
 * @returns {string[]} Array of created rule IDs
 */
function addRulesFromIteratorResult(result, feature) {
  if (!result || !result.fixes || !Array.isArray(result.fixes)) return [];

  const createdIds = [];
  for (const fix of result.fixes) {
    if (!fix.description) continue;

    const id = addRule({
      category: fix.category || 'architecture',
      description: `Prevent recurrence: ${fix.description}`,
      severity: fix.severity || 'medium',
      detection: { type: 'pattern', pattern: fix.description },
      detectedInFeature: feature,
      autoGenerated: true,
    });
    createdIds.push(id);
  }

  return createdIds;
}

// ============================================================
// Regression Detection
// ============================================================

/**
 * @typedef {Object} RegressionHit
 * @property {string} ruleId - Matched rule ID
 * @property {string} category - Rule category
 * @property {string} severity - Rule severity
 * @property {string} description - Rule description
 * @property {string} [metricId] - Metric that triggered the hit
 * @property {number} [currentValue] - Current metric value
 * @property {number} [threshold] - Rule threshold
 */

/**
 * Detect regressions by checking current metrics against all metric-based rules.
 * @param {Record<string, number>} metrics - Current metric values keyed by metric ID
 * @param {string} [feature] - Feature name (filter rules, or check all if null)
 * @returns {{detected: boolean, regressions: RegressionHit[]}}
 */
function detectRegressions(metrics, feature) {
  const rules = loadRules(null, null); // Load all rules
  const regressions = [];

  for (const rule of rules) {
    if (rule.detection.type !== 'metric') continue;
    if (!rule.detection.metricId || !rule.detection.op) continue;

    const currentValue = metrics[rule.detection.metricId];
    if (currentValue == null) continue;

    const threshold = rule.detection.threshold;
    if (threshold == null) continue;

    let violated = false;
    switch (rule.detection.op) {
      case '>': violated = currentValue > threshold; break;
      case '>=': violated = currentValue >= threshold; break;
      case '<': violated = currentValue < threshold; break;
      case '<=': violated = currentValue <= threshold; break;
      case '===': violated = currentValue === threshold; break;
      default: break;
    }

    if (violated) {
      regressions.push({
        ruleId: rule.id,
        category: rule.category,
        severity: rule.severity,
        description: rule.description,
        metricId: rule.detection.metricId,
        currentValue,
        threshold,
      });

      // Increment violation counter
      _incrementViolation(rule.id);
    }
  }

  return {
    detected: regressions.length > 0,
    regressions,
  };
}

/**
 * Increment the violation counter for a specific rule.
 * @param {string} ruleId - Rule ID to increment
 * @private
 */
function _incrementViolation(ruleId) {
  const data = stateStore.read(_rulesPath());
  if (!data || !data.rules) return;

  const rule = data.rules.find(r => r.id === ruleId);
  if (rule) {
    rule.violations = (rule.violations || 0) + 1;
    data.lastUpdated = new Date().toISOString();
    stateStore.write(_rulesPath(), data);
  }
}

/**
 * Compare current metrics with previous metrics to detect metric-level regressions.
 * Returns any metrics that have worsened beyond a significance threshold.
 *
 * @param {Record<string, number>} currentMetrics - Current metric values keyed by metric ID (M1-M10)
 * @param {Record<string, number>} previousMetrics - Previous metric values keyed by metric ID
 * @returns {Array<{metricId: string, current: number, previous: number, delta: number}>}
 */
function checkMetricRegression(currentMetrics, previousMetrics) {
  if (!currentMetrics || !previousMetrics) return [];

  // Import METRIC_SPECS to determine direction
  const { METRIC_SPECS } = require('./metrics-collector');

  const regressions = [];

  for (const [metricId, spec] of Object.entries(METRIC_SPECS)) {
    const current = currentMetrics[metricId];
    const previous = previousMetrics[metricId];

    if (current == null || previous == null) continue;

    const delta = current - previous;

    // Check if metric worsened (considering direction)
    let regressed = false;
    if (spec.direction === 'higher' && delta < -2) {
      regressed = true; // Higher is better, but value decreased by >2
    } else if (spec.direction === 'lower' && delta > 2) {
      regressed = true; // Lower is better, but value increased by >2
    }

    if (regressed) {
      regressions.push({ metricId, current, previous, delta });
    }
  }

  return regressions;
}

// ============================================================
// Maintenance
// ============================================================

/**
 * Remove rules older than maxAgeDays that have zero violations.
 * Rules with violations are preserved regardless of age.
 *
 * @param {number} [maxAgeDays=90] - Maximum age in days for zero-violation rules
 * @returns {number} Number of pruned rules
 */
function pruneStaleRules(maxAgeDays) {
  const maxAge = (maxAgeDays || 90) * 24 * 60 * 60 * 1000;
  const data = stateStore.read(_rulesPath());
  if (!data || !data.rules) return 0;

  const now = Date.now();
  const before = data.rules.length;

  data.rules = data.rules.filter(rule => {
    // Keep rules with violations
    if (rule.violations > 0) return true;

    // Check age
    const age = now - new Date(rule.createdAt).getTime();
    return age <= maxAge;
  });

  const pruned = before - data.rules.length;
  if (pruned > 0) {
    data.lastUpdated = new Date().toISOString();
    stateStore.write(_rulesPath(), data);
  }

  return pruned;
}

// ============================================================
// Exports
// ============================================================

module.exports = {
  loadRules,
  addRule,
  addRulesFromIteratorResult,
  detectRegressions,
  checkMetricRegression,
  pruneStaleRules,
};
